### PR TITLE
Fix test step parsing

### LINKED ISSUE #10: Parsing gherkin steps doesn't handle strings properly
For a Gherkin step that has a string in quotes, the contents of the quotes end up as part of the expected method name, rather than as arguments to the method the way they should.

### PR DESCRIPTION
**Pull request by forevermatt**
Fixes #10 

Also begins progress on #7 

Once this is merged, I plan to do another release

### CODE REVIEW

File: src/StepParser.php [hunk 1]
```diff
@@ -0,0 +1,101 @@
...
+            }
+            
+            $functionName .= self::formatForFunctionName($word);
+        }
+        
+        $this->functionName = $functionName;
+        $this->arguments = $arguments;
+    }
+    
+    public static function tokenize(string $stepText)
```
Comment (longrunningprocess) [inline src/StepParser.php:39]: consider some existing tokenizers if they exist, especially anything already built into PHP

Comment (forevermatt) [reply src/StepParser.php:39]: So far I'm not finding anything that looks helpful. If you happen across something that looks promising, feel free to mention it. In the meantime, I'll continue with my custom tokenizer until I find a better option. Thanks for the suggestion, though.
