### PR TITLE
Return a non-zero exit code for failures

### LINKED ISSUE #5: Return non-zero exit code if tests fail
This will probably also require changing how I write output to the console during tests, so that progress can be written out, but an exception still thrown for a failure (without losing the console output).

As of version 0.1.0, all the console output is returned as a string, so the `run-tests.php` file's code doesn't actually know whether things passed or failed. It will need to in order to return an appropriate exit code.

### PR DESCRIPTION
**Pull request by forevermatt**
Fixes #5 

Also fixes a few line-endings

### CODE REVIEW

File: src/BasicLogger.php [hunk 1]
```diff
@@ -0,0 +1,18 @@
...
+     * Log a message.
+     *
+     * @param mixed $level
+     * @param string $message
+     * @param array $context
+     * @return null
+     */
+    public function log($level, $message, array $context = [])
+    {
+        echo $this->interpolate($message, $context) . PHP_EOL;
```
Comment (longrunningprocess) [inline src/BasicLogger.php:16]: was simply using the `LoggerBase.interpolate` not an option?  Just wondering why you needed this wrapper?

**Review by longrunningprocess — APPROVED** [review]

File: src/BasicLogger.php (hunk 1 above)
Comment (forevermatt) [reply src/BasicLogger.php:16]: LoggerBase was still an abstract class, basically to provide the interpolate code so that all a subclass/implementation would have to do was provide a `log()` method. Thanks for asking, though. :-)
